#!/usr/bin/env python3

import scrapy



class QuotesSpider(scrapy.Spider):
    name = "fleaflicker"

    def start_requests(self):
        urls = [
            'https://www.fleaflicker.com/mlb/leagues/21579/teams'
        ]
        for url in urls:
            yield scrapy.Request(url=url, callback=self.parse)

    def parse(self, response):
        page = response.url.split("/")[-2]
        filename = 'quotes-%s.html' % page
        with open(filename, 'wb') as f:
            f.write(response.body)
        self.log('Saved file %s' % filename)



